apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: binder
spec:
  acme:
    email: swarup@datakaveri.org
    server: https://acme-v02.api.letsencrypt.org/directory
    # use staging URL when testing setup or you may get blocked by letsencrypt for 12 hours
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx