kind: ConfigMap
apiVersion: v1
metadata:
  name: jupyter-config
data:
  jupyter_config.json: |-
    {
      "VoilaConfiguration": {
          "enable_nbextensions": true,
          "template": "vuetify-default",
          "extension_language_mapping": {
              ".py": "python",
              ".jl": "julia"
          },
          "language_kernel_mapping": {
              "python": "python3"
          }
        }
    }