apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sandboxserver-ingress
  namespace: binder
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.sandbox.iudx.io
    secretName: api-sandbox-iudx-io-tls
  rules:
    - host: api.sandbox.iudx.io
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: sandboxserver
              port:
                number: 8080
